### ISSUE TITLE
Find quad huts on predetermined seed.

### ISSUE THREAD

**Issue by dG9hc3Q** [hube12/quadHut#1]
Title says it all but basically the ability to enter a seed and see the coordinates of all the quad witch huts to the world border.

**Comment by dG9hc3Q** [comment]
Didn't realize you already made another repo doing this

**Comment by hube12** [comment]
indeed, I usually try to cover as many situation as possible, If you have others ideas or tools that you would find useful, don't hesitate to ask so ;)
